<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-30T15:42:50 IST" name="Suite" finished-at="2025-03-30T15:43:04 IST" duration-ms="14011">
    <groups>
    </groups>
    <test started-at="2025-03-30T15:42:50 IST" name="Testing" finished-at="2025-03-30T15:43:04 IST" duration-ms="13501">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="openapplication()[pri:0, instance:tests.LoginTest@60db1c0e]" started-at="2025-03-30T15:42:50 IST" name="openapplication" finished-at="2025-03-30T15:42:59 IST" duration-ms="8538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@60db1c0e]" started-at="2025-03-30T15:42:59 IST" name="login" data-provider="getLoginData" finished-at="2025-03-30T15:43:03 IST" duration-ms="4693" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bhargava372@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Bhargava#96]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sucessful]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.LoginTest@60db1c0e]" started-at="2025-03-30T15:43:03 IST" name="teardown" finished-at="2025-03-30T15:43:04 IST" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Testing -->
    <test started-at="2025-03-30T15:42:50 IST" name="TestingThree" finished-at="2025-03-30T15:43:04 IST" duration-ms="13603">
      <class name="tests.Testthree">
        <test-method signature="Threetest()[pri:0, instance:tests.Testthree@5be1d0a4]" started-at="2025-03-30T15:42:50 IST" name="Threetest" finished-at="2025-03-30T15:43:04 IST" duration-ms="13572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Threetest -->
      </class> <!-- tests.Testthree -->
    </test> <!-- TestingThree -->
    <test started-at="2025-03-30T15:42:50 IST" name="TestingTwo" finished-at="2025-03-30T15:43:04 IST" duration-ms="14011">
      <class name="tests.Testtwo">
        <test-method signature="teststwo()[pri:0, instance:tests.Testtwo@5884a914]" started-at="2025-03-30T15:42:50 IST" name="teststwo" finished-at="2025-03-30T15:43:04 IST" duration-ms="13491" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.Testtwo.teststwo(Testtwo.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststwo -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.Testtwo@5884a914]" started-at="2025-03-30T15:43:04 IST" name="closure" finished-at="2025-03-30T15:43:04 IST" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- tests.Testtwo -->
    </test> <!-- TestingTwo -->
  </suite> <!-- Suite -->
</testng-results>
